### ISSUE TITLE
Event for start must be called 'MY_EVENT_STARTED'

### ISSUE THREAD

**Issue by nickbullock** [machadogj/redux-thunk-actions#8]
But in code we can see 'MY_EVENT_START'.
All another events names ends with 'ED'.
https://github.com/machadogj/redux-thunk-actions/blob/9586b542847fb07573690520e63d9131b8eb3cce/src/index.js#L11
https://github.com/machadogj/redux-thunk-actions/blob/9586b542847fb07573690520e63d9131b8eb3cce/src/index.js#L61

**Comment by machadogj** [comment]
@nickbullock thanks for the feedback! I just added this in 1.3.2 (it's backwards compatible)
